# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 03:07
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='stock_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19),
        ),
    ]
